#!/usr/bin/env bash
set -euo pipefail

cd -- "$(dirname -- "${BASH_SOURCE[0]}")"

COMPOSE_FILE="${COMPOSE_FILE:-compose.yaml}"
if [[ ! -f "$COMPOSE_FILE" ]]; then
    echo "Compose file not found: $COMPOSE_FILE" >&2
    exit 1
fi

compose=(docker compose -f "$COMPOSE_FILE")
if [[ "$COMPOSE_FILE" -ef compose.yaml ]]; then
    # Discover permission groups; the device directory itself supports hot-plugging.
    override=compose.override.yaml
    marker="# Generated by rebuild-and-restart.sh; do not edit."
    if [[ -f "$override" ]] && [[ "$(head -n 1 "$override")" != "$marker" ]]; then
        echo "Refusing to overwrite existing $override; move it before generating camera mappings." >&2
        exit 1
    fi
    temporary=$(mktemp .camera-devices.XXXXXX)
    trap 'rm -f -- "$temporary"' EXIT
    declare -A camera_groups=()
    camera_paths=()
    video_group=$(getent group video | cut -d: -f3 || true)
    if [[ -n "$video_group" ]]; then camera_groups["$video_group"]=1; fi
    shopt -s nullglob
    for device in /dev/video[0-9]* /dev/v4l/by-id/*; do
        [[ "$device" =~ ^/dev/(video[0-9]+|v4l/by-id/[A-Za-z0-9_.+-]+)$ ]] || continue
        [[ -c "$device" ]] || continue
        [[ "$(stat -Lc '%t' "$device")" == "51" ]] || continue  # V4L2 major 81
        camera_paths+=("$device")
        camera_groups["$(stat -Lc '%g' "$device")"]=1
    done
    # DSLR USB nodes can use plugdev or another host permission group.
    # Do not add group 0; use the documented video-group udev rule instead.
    for device in /dev/bus/usb/[0-9][0-9][0-9]/[0-9][0-9][0-9]; do
        [[ -c "$device" ]] || continue
        [[ "$(stat -Lc '%t' "$device")" == "bd" ]] || continue  # USB major 189
        usb_group=$(stat -Lc '%g' "$device")
        if [[ "$usb_group" != "0" ]]; then camera_groups["$usb_group"]=1; fi
    done
    {
        printf '%s\nservices:\n  grow:\n' "$marker"
        if (( ${#camera_groups[@]} )); then
            printf '    group_add:\n'
            for group in "${!camera_groups[@]}"; do
                printf '      - "%s"\n' "$group"
            done
        else
            printf '    group_add: []\n'
        fi
    } > "$temporary"
    mv -- "$temporary" "$override"
    echo "Detected ${#camera_paths[@]} video paths; USB permission groups included for DSLRs. Cameras can be connected after startup."
    compose+=(-f "$override")
fi

echo "Using compose file: $COMPOSE_FILE"
echo "Rebuilding services..."
"${compose[@]}" build

echo "Recreating and restarting services..."
"${compose[@]}" up -d --force-recreate --wait --wait-timeout 60
"${compose[@]}" ps

echo "Done."
